app:
  auth:
    fake: ${app.auth.fake:true}

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: expense-tracker
  datasource:
    url: jdbc:postgresql://${db.host:localhost}:${db.port:5432}/${db.name:expensetracker}
    username: ${db.username:expensetracker}
    password: ${db.password:expensetracker}
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    show-sql: false
  flyway:
    enabled: true
  threads:
    virtual:
      enabled: true

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    com.expensetracker: INFO
